name: Deployment Application
on:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Installation of dependencies
        run: npm ci
      - name: Starting ESLint
        run: npm run lint
      - name: Starting Stylelint
        run: npm run stylelint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Installation of dependencies
        run: npm ci
      - name: Starting Unit test
        run: npm run test:unit
      - name: Starting Screenshot test
        run: |
          npm run storybook:build
          npm run test:ui:ci

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Installation of dependencies
        run: npm run ci
      - name: Building App for prodaction
        run: npm run build:prod
