name: Deployment Application
on:
  push:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Installation of dependencies
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Starting ESLint
        run: npm run lint
      - name: Starting Stylelint
        run: npm run stylelint
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Starting Unit test
        run: npm run test:unit
      - name: Starting Screenshot test
        run: |
          npm run storybook:build
          npx loki --requireReference --reactUri file:./storybook-static
  build:
    runs-on: ubuntu-latest
    needs: [setup, lint, test]
    steps:
      - name: Building App for prodaction
        run: npm run build:prod
